import BlogWrapper from '@/components/Blog/BlogWrapper'
import Hero from '@/components/Hero/Hero'
import Container from '@/components/Layout/Container'
import Wave from '@/components/Wave'
import Head from 'next/head'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Praveen kr. | 🏡</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Hero />
      </Container>
      <Wave />
      <Container center={true}>
        <BlogWrapper />
      </Container>

    </div >

  )
}
